### ISSUE TITLE
Delay Window Not Delaying Rewards

### ISSUE THREAD

**Issue by Master1122334455** [risograph/HiRewards#3]
Hello,
First off love the plugin so far and glad to see you got the Displayname changed out for name as we were seeing some issues with that.
Secondly we seem to be having issues with the delay time between being rewarded for the same player. It's set to the default of 8 hours and we haven't changed much in the config.

```yml
# HiRewards 👋
# by riso
#
# HiRewards is a plugin that gives customizable rewards to players
# who greet incoming players or those joining for the first time!

# Valid Greetings
# - The words which you would like to trigger the reward
# - Supports Regex
# Example:
#   - ".*welcome*."
#   - ".*h?ello*."
greetings:
  - "Welcome"
  - "Wb"

# Response Time
# In SECONDS, amount of time all players have to greet an
# incoming player before they can no longer receive a reward.
#
# Default: 20
response_time: 30

# Rewards
# Run as commands, rewards that are given to the player
# after a valid greeting.
# Supports all kinds of commands, so consider sending
# tellraw or title!
#
# Example:
#   - "eco give %player% 25"
#   - "give %player% diamond 1"
#
# List of all Bukkit-supported sounds:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
rewards:
  firstjoin:
    sound:
      name: entity.experience_orb.pickup
      volume: 10
      pitch: 2
    commands:
      - "eco give %player% 2500"
  join:
    sound:
      name: entity.experience_orb.pickup
      volume: 10
      pitch: 1.7
    commands:
      - "eco give %player% 1000"

# Reward Cooldown
# In HOURS, the time required for player to receive reward for
# greeting the same player.
#
# Default: 8
reward_cooldown: 8
```

![Image](https://github.com/user-attachments/assets/f1dd682e-0dca-4861-9e68-5b50e595495b)

Here is how the DB looks.
16d28b5e-9e39-47f0-b424-3b8054a26990 | a7b0f3e7-ecdf-4df3-833d-876fcbc99ea4 | 1733795824990
